/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/yenn/catkin_ws/src/adns3080_msg/msg/Adns3080.msg
 *
 */


#ifndef ADNS3080_MSG_MESSAGE_ADNS3080_H
#define ADNS3080_MSG_MESSAGE_ADNS3080_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace adns3080_msg
{
template <class ContainerAllocator>
struct Adns3080_
{
  typedef Adns3080_<ContainerAllocator> Type;

  Adns3080_()
    : header()
    , flow_x(0)
    , flow_y(0)
    , quality(0)
    , overflow(false)
    , distance(0.0)  {
    }
  Adns3080_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , flow_x(0)
    , flow_y(0)
    , quality(0)
    , overflow(false)
    , distance(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _flow_x_type;
  _flow_x_type flow_x;

   typedef int8_t _flow_y_type;
  _flow_y_type flow_y;

   typedef uint8_t _quality_type;
  _quality_type quality;

   typedef uint8_t _overflow_type;
  _overflow_type overflow;

   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::adns3080_msg::Adns3080_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adns3080_msg::Adns3080_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Adns3080_

typedef ::adns3080_msg::Adns3080_<std::allocator<void> > Adns3080;

typedef boost::shared_ptr< ::adns3080_msg::Adns3080 > Adns3080Ptr;
typedef boost::shared_ptr< ::adns3080_msg::Adns3080 const> Adns3080ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adns3080_msg::Adns3080_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adns3080_msg::Adns3080_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace adns3080_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'adns3080_msg': ['/home/yenn/catkin_ws/src/adns3080_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::adns3080_msg::Adns3080_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adns3080_msg::Adns3080_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adns3080_msg::Adns3080_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adns3080_msg::Adns3080_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adns3080_msg::Adns3080_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adns3080_msg::Adns3080_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adns3080_msg::Adns3080_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c57aad807ebfede48cbe6e9d4ef3315";
  }

  static const char* value(const ::adns3080_msg::Adns3080_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c57aad807ebfedeULL;
  static const uint64_t static_value2 = 0x48cbe6e9d4ef3315ULL;
};

template<class ContainerAllocator>
struct DataType< ::adns3080_msg::Adns3080_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adns3080_msg/Adns3080";
  }

  static const char* value(const ::adns3080_msg::Adns3080_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adns3080_msg::Adns3080_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int8 flow_x\n\
int8 flow_y\n\
uint8 quality\n\
bool overflow\n\
float32 distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::adns3080_msg::Adns3080_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adns3080_msg::Adns3080_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.flow_x);
      stream.next(m.flow_y);
      stream.next(m.quality);
      stream.next(m.overflow);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Adns3080_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adns3080_msg::Adns3080_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adns3080_msg::Adns3080_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flow_x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flow_x);
    s << indent << "flow_y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flow_y);
    s << indent << "quality: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.quality);
    s << indent << "overflow: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overflow);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADNS3080_MSG_MESSAGE_ADNS3080_H
